#include <stdio.h>

void helpmsg(int vma, int vmi) {
	printf(
"PISHELL %d.%d\n(c) ADITYA KUMAR 2024\n\n\
PISHELL IS A SIMPLE SHELL WRITTEN IN C++ FOR\n\
EMBEDDED SYSTEMS.\n\
\n\
COMMANDS ARE NOT CASE-SENSITIVE.\n\
ARGUMENTS ARE LISTED IN THE ORDER THEY APPEAR\n\
USING ALPHABETS A-Z.\n\
\n\
BASIC OPERATIONS\n\
EXIT\tEXIT THE SHELL\n\
ECHO\tPRINT EVERYTHING AFTER THIS COMMAND\n\
INPUT\tSTORE IN REGISTER A THE INTEGER VALUE\n\
\tENTERED IN THE NEXT LINE\n\
HELP\tDISPLAY THIS MESSAGE\n\
\n\
MEM\tRETURN NUMBER OF REGISTERS AVAILABLE AND\n\
\tFUNCTION DEFINITION LIMITATIONS\n\
SET\tSET REGISTER A TO VALUE B\n\
VAL\tPRINT VALUE OF REGISTER A\n\
DROP\tSET ALL REGISTERS TO ZERO\n\
SHOW\tPRINT ALL REGISTERS ON SCREEN\n\
\n\
AND\tSTORE RESULT OF LOGICAL AND OF A, B\n\
\tIN C\n\
OR\tSTORE RESULT OF LOGICAL OR OF A, B\n\
\tIN C\n\
ADD\tSTORE RESULT OF A+B IN C\n\
SUB\tSTORE RESULT OF A-B IN C\n\
MUL\tSTORE RESULT OF A*B IN C\n\
DIV\tSTORE RESULT OF A/B IN C\n\
INV\tSTORE RESULT OF LOGICAL NOT OF A IN B\n\
BLINV\tSTORE RESULT OF BOOLEAN INVERSE OF A\n\
\tIN B\n\
CMP\tEVALUATE EXPRESSION A OP B WHERE OP CAN\n\
\tBE <, >, =, <=, >=, !=\n\
STCMP\tSTORE RESULT OF MOST RECENT CMP IN\n\
\tREGISTER A\n\
\n\
DEFINING A FUNCTION\n\
TO DEFINE A FUNCTION, USE THE DEFFXN INST.\n\
PROVIDE A NAME TO THE FUNCTION AS FIRST ARG.\n\
ALL SUBSEQUENT COMMANDS ARE CACHED AS\n\
PART OF THE DEFINED FUNCITON.\n\
END FUNCTION DEFINITION BY ENDFXN INST.\n\
NESTED FUNCITONS ARE NOT SUPPORTED AND WILL\n\
LEAD TO UNDEFINED BEHAVIOR\n\
\n\
DEFFXN\tSTART DEFINING FUNCTION A\n\
ENDFXN\tFINISH DEFINING FUNCTION\n\
JMPT\tIF PREVIOUS CMP EVALUATED TRUE,\n\
\tJUMP TO THE FUNCTION A.\n\
JMP\tJUMP TO FUNCTION A UNCONDITIONALLY.\n\
SNIT\tSKIP NEXT INSTRUCTION IF PREVIOUS CMP\n\
\tEVALUATED TRUE\n\
LFXN\tLIST ALL DEFINED FUNCTIONS\n\
\n",
		vma, vmi
	);
}